### ISSUE TITLE
SORTCHANNELS usage unclear

### ISSUE THREAD

**Issue by alanman87** [jjssoftware/m3u-epg-editor#10]
I couldn't get this to work pointing at a txt file I built from the channel list. How is this argument used? Please provide an example.

**Comment by jjssoftware** [comment]
The --sortchannels / -s argument is a list of channel names for channels within those groups that you want to keep where those channel names are specified in your desired channel sort order.

I've added abbreviated examples in the sample usage calls in the readme:

https://github.com/jjssoftware/m3u-epg-editor/blob/master/README.md
