### ISSUE TITLE
Enhancement: RegEx support for --channels [CHANNELS], -c [CHANNELS]

### ISSUE THREAD

**Issue by spec1re** [jjssoftware/m3u-epg-editor#14]
It would be very handy, if there where RegEx support for --channels [CHANNELS], -c [CHANNELS], so one pattern would catch many, eg. to discard placeholders and unwanted channels:

without RegEx
```
-c="
'willow hd',
'bein sports espanol hd',
'### Placeholder AB 71 ###',
'### Platzhalter DFG 2 ###',
'### Metacarattere J 3 ###',
'### Algildistakn LM 4 ###',
'### Bosluk OPQRST 445 ###',
'Channel 1 SD',
'Kannal 22 SD',
'Canal 763 SD',
'Kanaal 54 SD',
'Stretto 9 SD'
"
```
with RegEx
```
-c="
'willow hd',
'\w+ \w+ espanol \w+',       // No hablo español
'### \w+ \w+ \d+ ###',       // Get rid of all dummy channels
'\w+ \d+ SD'                 // SD meeeh
"
```
As some IPTV providers update their m3u lists frequently, there would still no need to touch the config line.

**Comment by jjssoftware** [comment]
Thanks that sounds like a decent feature. I'll take a look asap.

**Comment by jjssoftware** [comment]
Hopefully that should do it. Please watch your regex expressions though; i.e. you might have intended your last one to look like this `'(\\w*|\\d*)SD'` to enable it to skip any characters up to the SD matched at the end.

See how you go with it anyway, just let me know if you see any issues.

**Comment by jjssoftware** [comment]
Thanks for the update @spec1re much appreciated
