### ISSUE TITLE
Starting value argument for channel numbers

### ISSUE THREAD

**Issue by jobrien2001** [jjssoftware/m3u-epg-editor#20]
Hello

I am looking to run this on 2 different m3us and do not want the channel numbers to overlap.  I cant merge the m3u before hand because of reasons...

It would be great to have a starting value for channel numbering so that it does not always start at 1.

Thanks

**Comment by jjssoftware** [comment]
Hi there

I think that you're requesting the introduction of a new argument that would work with the existing `--tvh_offset / -t` argument i.e. something like `--tvh_start / -ts`.

When specified, this value would be used as the absolute start of numbering for the tvh-chnum attribute values on channels.

Do I understand correctly?

Cheers

**Comment by jobrien2001** [comment]
Yes, exactly

**Comment by jjssoftware** [comment]
ok I'll take a look later, it sounds reasonable and easy enough

**Comment by jjssoftware** [comment]
That should do it, tested working here.
