### ISSUE TITLE
Can we select and run only one or two groups of channels, through the m3u link?

### ISSUE THREAD

**Issue by bidaro** [jjssoftware/m3u-epg-editor#21]
Hi

Can we select and run only one or two groups of channels, through the m3u link?
Example, add code!

Thank you

**Comment by jjssoftware** [comment]
Hi @bidaro,

The --groups / -g argument is an array, you can pass / configure as many channel groups as you want / need.

There are command line examples in the [readme sample usage calls](https://github.com/jjssoftware/m3u-epg-editor/blob/master/README.md#sample-usage-calls-urls-intentionally-incomplete) section and there's a sample json configuration file [here](https://github.com/jjssoftware/m3u-epg-editor/blob/master/sample_input_args.json)

Cheers
