### ISSUE TITLE
Groups Get

### ISSUE THREAD

**Issue by wlatic** [jjssoftware/m3u-epg-editor#22]
This isnt an issue but more a feature request.

Would it be possible to add in a function to group only the groups?

Would make getting the config setup a little easier!

**Comment by wlatic** [comment]
To help i've been using the following command:
 grep -o -P '(?<=group-title=").*(?=")' original.m3u8 | uniq

**Comment by jjssoftware** [comment]
Hi @wlatic,

I can see that your grep command outputs the content of all distinct group-title attributes from the given m3u file, sorted alphabetically.

I'm not entirely clear what this feature request is requesting at present, hopefully you can clarify. What is "a function to group only the groups" asking for ? 

Are you requesting that all channel groups from the original source m3u file be output into i.e. a new original.groups.txt file to help with initial config setup ? 

Are you aware that all channels from the original source m3u file are output into the original.channels.txt file along with their channel group ? 

Please let me know

Cheers,
Joe

**Comment by jjssoftware** [comment]
I'm going to close this because there's been no further comms to clarify exactly what is needed. If you want to clarify / supply more details, reopen it.
