### ISSUE TITLE
Group regex

### ISSUE THREAD

**Issue by Fietspomp86** [jjssoftware/m3u-epg-editor#24]
Hi,

Love this project. 
Is it possible to add the regex function also to groups?
I'm using "mytvonline" provider and each group-title also contains the channel name. (I know it's stupid).

Here's an example of a line in the m3u file.
`#EXTINF:-1 tvg-id="NPO1.nl" tvg-name="NL4K+ | NPO 1" tvg-logo="http://mytvonline.nl/picons/npo1hd.png" group-title="TV 4K+ | Nederland",NL4K+ | NPO 1`

Thanks!

**Comment by jjssoftware** [comment]
Hi there, 

Yes I'm sure I'll be able to work something out to enable regex pattern matching against groups to be kept. 

This is a good idea for a feature request but I agree, if someone somewhere has decided to include channel names within group names that does seem..silly. 

Leave it with me and I'll take a look asap. 

Cheers
Joe

**Comment by jjssoftware** [comment]
There you go @Fietspomp86, one change committed directly to the master branch.

This change extends the `--groups / -g [GROUPS]` argument, hopefully it should enable you to configure one or more regex patterns to match against whatever group text contains the good stuff.

Please update and give it a go, cheers.

**Comment by Fietspomp86** [comment]
Great that you fixed it so quickly. Any chance there's somewhere a list how to use these regex? Can't seem to get it working.

**Comment by jjssoftware** [comment]
No problem, it's good to hear that you got it working. Regular expressions can be one of the most complex error-prone things known to man in my opinion.
