### ISSUE TITLE
regex in group filter

### ISSUE THREAD

**Issue by kaczy44** [jjssoftware/m3u-epg-editor#25]
Hi,
It seems that regex not working or I don't know how to use it...
I have: -g="'LIVE: .*'" in command line, but there are 0 results.
Could someone advise how to use regex in groups properly ?

**Comment by jjssoftware** [comment]
Hi there, include your complete command line (sanitized, any username / password removed) and describe what it is that you're attempting to match on and I'll take a look when I can.

**Comment by kaczy44** [comment]
`python ./m3u-epg-editor.py -m="http://**.*********.****.***/get.php?username=****************&password=**********&type=m3u_plus&output=ts" -g="'LIVE: .*'" --sortchannels --no_epg --no_tvg_id --http_for_images --log_enabled -d="./output" -f="output_file"
`

There are many groups named LIVE: ******* or SERIES: ********** or MOVIES: ************* and I would like to get rid of all except LIVE: ******* groups. I'm on Windows if it matters...

**Comment by jjssoftware** [comment]
ah ok, I understand. I'm out for the day today but I'll take a look asap.

**Comment by jjssoftware** [comment]
Something like this should work:

`python ./m3u-epg-editor.py -m="http://**.*********.****.***/get.php?username=****************&password=**********&type=m3u_plus&output=ts" -g="'(?i)^LIVE:.+'" -ne -nt -hi -l -d="./output" -f="output_file"`

Here's an explanation for the `'(?i)^LIVE:.+'` regular expression:

1. `(?i)` specifies that case insensitive matching is enabled
2. `^LIVE:` specifies that those strings that have the substring `"LIVE:"` at the start will be matched
3. `.+` specifies that any characters to the end of the string are permitted following a successful match

Give that a whirl.

**Comment by kaczy44** [comment]
It works!! Thank you so much!!

**Comment by jjssoftware** [comment]
Great. To be fair this issue did highlight an issue with this feature: this only currently works as expected when `(?i)` is included in the regex to force it to work in a case-insensitive manner. That is not really intuitive self explanatory behaviour and it's not reasonable to expect people to guess this is how it works so I'm going to take a look at improving this so that this is not needed and so that it's easier to get it working.
