### ISSUE TITLE
Enhancement - be able to grab local files

### ISSUE THREAD

**Issue by haxcop** [jjssoftware/m3u-epg-editor#4]
HI, 
It's possible to adjust the code to grab also a local m3u8 file and xml?. I have test those methods and currently it's not.
I have also tried using a local file with the method:
`file:///C:/Users/Carlos/Documents/Plex-Scripts/development/telly/tests/sorted.m3u8`
But not luck 
This could help with automation in many thinkable ways. 

Thanks in advance.

**Comment by jjssoftware** [comment]
Hi there,

I'm sure it is possible to implement a change like this. I was surprised to find that a file uri doesn't work as-is but it would appear that it's just something that the requests module doesn't natively support. 

I don't have any need for this myself but feel free to give it a try in a fork if you feel like. I don't have the time myself at the moment. I'll accept a pull request if it's a platform independent general enough change.

**Comment by haxcop** [comment]
@jjssoftware Thanks for the chance. I am kinda busy too right now but I'll see what I can do  :)

**Comment by jjssoftware** [comment]
Hi @haxcop I don't know if you did anything with this yet but I found the time to play around today and I have a version of the script that supports local file uris in my file_uris dev branch here:

https://github.com/jjssoftware/m3u-epg-editor/tree/file_uris

Feel free to give it a try. If you do, please let me know what you think and let me know if it works for you. It seems to be working ok here on linux from what I've tested so far.

**Comment by jjssoftware** [comment]
Introduced support for local file Uris for both the m3u file and epg file.
