### ISSUE TITLE
ffmpeg pipe patch

### ISSUE THREAD

**Issue by psycho-driver** [jjssoftware/m3u-epg-editor#40]
This patch adds an -ffmpeg option which will embed the stream url in an ffmpeg pipe for providers which use non-standard mpegts streams

[ffmpeg-pipe.patch.gz](https://github.com/jjssoftware/m3u-epg-editor/files/4004401/ffmpeg-pipe.patch.gz)

**Comment by jjssoftware** [comment]
I'm not sure if this is a feature that I would be willing to merge but feel free to create a pull request and I'll take a look.
