### ISSUE TITLE
Error parsing XML file

### ISSUE THREAD

**Issue by arjunior26** [jjssoftware/m3u-epg-editor#48]
Hi,

My actual XML file contains some invalid character which leads to an error when parsing epg file.
So I modify the script to use lxml library and XMLParser class with recover argument :
```
from lxml.etree import Element, SubElement, parse, ElementTree, XMLParser
...
def create_new_epg(args, original_epg_filename, m3u_entries):
    output_str("creating new xml epg for {} m3u items".format(len(m3u_entries)))
    try:
        #original_tree = parse(original_epg_filename)
        parser = XMLParser(recover=True)
        original_tree = parse(original_epg_filename, parser)
        ...
```
What do you think about using it ? That shouldn't be a problem except we have to install one more package.

**Comment by jjssoftware** [comment]
haha ok, I'll take a look. I have to say that I'm noticing a common theme with your 3 issues, in one way or another they're all data quality related 😃

**Comment by arjunior26** [comment]
You're right :))

**Comment by jjssoftware** [comment]
I like this suggestion, thank you. Making the change now.

**Comment by jjssoftware** [comment]
Done, thanks.

**Comment by arjunior26** [comment]
Thank you !
