### ISSUE TITLE
Escaping "|" in -g parameter

### ISSUE THREAD

**Issue by Calimerorulez** [jjssoftware/m3u-epg-editor#55]
Hi!

How can I filter a group-title which contains a pipe, like `"|NL| KLASSIEK"`?

If I use `-g="'\|NL\| KLASSIEK'"` it outputs nothing. If I use `-g="'|NL| KLASSIEK'"` the output is more than only that group.

**Comment by jjssoftware** [comment]
try `-g="'\\|NL\\| KLASSIEK'"`

**Comment by Calimerorulez** [comment]
Thanks, that works great :)

**Comment by jjssoftware** [comment]
👍
