### ISSUE TITLE
Commas in channel names mess everything up

### ISSUE THREAD

**Issue by hidefog** [jjssoftware/m3u-epg-editor#8]
It looks like if the channel name in the original m3u has a comma, it will break how that channel is recreated in the output file.
For example, it will take this:
`#EXTINF:-1 tvg-id="ABC (WKBW) Buffalo, NY HD" tvg-name="ABC East CA SD" tvg-logo="http://xxxxx/xxxx/picons/abceastcasd.png" group-title="US/CA Entertainment",ABC East CA SD`
And turn it into this:
`#EXTINF:-1 tvg-name="ABC East CA SD" tvg-id="ABC (WKBW) Buffalo, NY HD" tvg-logo="http://xxxxx/xxxx/picons/abceastcasd.png" group-title="US/CA Entertainment", NY HD" tvg-name="ABC East CA SD" tvg-logo="http://xxxxx/xxxx/picons/abceastcasd.png" group-title="US/CA Entertainment"`
When it should look like this:
`#EXTINF:-1 tvg-name="ABC East CA SD" tvg-id="ABC (WKBW) Buffalo, NY HD" tvg-logo="http://xxxxx/xxxx/picons/abceastcasd.png" group-title="US/CA Entertainment",ABC East CA SD`

I changed line 51 from this
`self.name = m3u_fields.split(",")[1]`
to this
`self.name = m3u_fields.split('",')[1]`

I'm not sure that's the best way to do it, but it seemed to fix my issue.

**Comment by jjssoftware** [comment]
Thanks for that, it's a fair point. I'll take a look to see what I can do to cope with it asap

**Comment by jjssoftware** [comment]
https://github.com/jjssoftware/m3u-epg-editor/commit/b32aa40ac0f8e04ff8b2751681dc93697de9b4a4 should resolve it - pretty much the same as your fix
